#!/usr/bin/env python3
"""
Compress linterdb.json with deflate and generate a C++ source file
containing the data as a byte array.

Usage:
    python embed_linterdb.py <linterdb.json> <output.cpp>

The generated file provides:
    extern const uint8_t  linterdb_compressed_data[];
    extern const uint32_t linterdb_compressed_size;
    extern const uint32_t linterdb_uncompressed_size;
"""

import sys
import zlib
import os


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <linterdb.json> <output.cpp>", file=sys.stderr)
        sys.exit(1)

    src_path = sys.argv[1]
    dst_path = sys.argv[2]

    with open(src_path, "rb") as f:
        raw = f.read()

    # Use raw deflate (no gzip header) — matches Godot's Compression::MODE_DEFLATE.
    compressed = zlib.compress(raw, 9)

    uncompressed_size = len(raw)
    compressed_size = len(compressed)

    print(f"linterdb: {uncompressed_size:,} -> {compressed_size:,} bytes "
          f"({compressed_size/uncompressed_size*100:.1f}%)")

    with open(dst_path, "w") as f:
        f.write("// Auto-generated by embed_linterdb.py — do not edit.\n")
        f.write("#include <cstdint>\n\n")
        f.write(f"extern const uint32_t linterdb_uncompressed_size = {uncompressed_size};\n")
        f.write(f"extern const uint32_t linterdb_compressed_size = {compressed_size};\n\n")
        f.write("extern const uint8_t linterdb_compressed_data[] = {\n")

        # Write in rows of 16 bytes.
        for i in range(0, len(compressed), 16):
            chunk = compressed[i:i+16]
            line = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"\t{line},\n")

        f.write("};\n")

    print(f"Written: {dst_path}")


if __name__ == "__main__":
    main()
