/**************************************************************************/
/*  homot_main.cpp                                                        */
/**************************************************************************/
/*  Unified entry point for homot toolchain.                              */
/*  Subcommands: lint, lsp, lspa                                         */
/*  Embeds compressed linterdb.json — no external DB file needed.         */
/**************************************************************************/

#ifdef HOMOT

#include "linter_run.h"
#include "lsp/lsp_server.h"
#include "lsp/lsp_transport.h"
#include "lspa/lspa_server.h"
#include "stubs/linterdb.h"

#include "modules/gdscript/gdscript.h"
#include "modules/gdscript/gdscript_cache.h"
#include "modules/gdscript/gdscript_utility_functions.h"
#include "modules/holymolly/register_types.h"

#include "core/config/engine.h"
#include "core/config/project_settings.h"
#include "core/io/dir_access.h"
#include "core/io/file_access.h"
#include "core/io/resource_loader.h"
#include "core/io/resource_saver.h"
#include "core/object/class_db.h"
#include "core/object/script_language.h"
#include "core/os/os.h"
#include "core/register_core_types.h"
#include "core/string/translation_server.h"
#include "servers/text/text_server.h"
#include "servers/text/text_server_dummy.h"

#ifdef _WIN32
#include "drivers/windows/dir_access_windows.h"
#include "drivers/windows/file_access_windows.h"
#endif

#include <cstdio>
#include <cstring>

#ifdef _WIN32
#include <fcntl.h>
#include <io.h>
#else
#include <unistd.h>
#endif

// ---------------------------------------------------------------------------
// Embedded linterdb (generated by embed_linterdb.py).
// ---------------------------------------------------------------------------

extern const uint8_t  linterdb_compressed_data[];
extern const uint32_t linterdb_compressed_size;
extern const uint32_t linterdb_uncompressed_size;

// ---------------------------------------------------------------------------
// Suppress stderr during static initialization.
// ---------------------------------------------------------------------------

static int _homot_saved_stderr_fd = -1;

#ifdef _WIN32
#pragma init_seg(compiler)
static struct _HomotStderrGuard {
	_HomotStderrGuard() {
		fflush(stderr);
		_homot_saved_stderr_fd = _dup(_fileno(stderr));
		FILE *nul = fopen("NUL", "w");
		if (nul) {
			_dup2(_fileno(nul), _fileno(stderr));
			fclose(nul);
		}
	}
} _homot_stderr_guard;
#else
__attribute__((constructor(101)))
static void _homot_suppress_stderr() {
	fflush(stderr);
	_homot_saved_stderr_fd = dup(fileno(stderr));
	FILE *nul = fopen("/dev/null", "w");
	if (nul) {
		dup2(fileno(nul), fileno(stderr));
		fclose(nul);
	}
}
#endif

static void _homot_restore_stderr() {
	if (_homot_saved_stderr_fd >= 0) {
		fflush(stderr);
#ifdef _WIN32
		_dup2(_homot_saved_stderr_fd, _fileno(stderr));
		_close(_homot_saved_stderr_fd);
#else
		dup2(_homot_saved_stderr_fd, fileno(stderr));
		close(_homot_saved_stderr_fd);
#endif
		_homot_saved_stderr_fd = -1;
	}
}

// ---------------------------------------------------------------------------
// Minimal OS
// ---------------------------------------------------------------------------

class OS_Homot : public OS {
protected:
	void initialize() override {}
	void initialize_joypads() override {}
	void set_main_loop(MainLoop *p_main_loop) override {}
	void delete_main_loop() override {}
	void finalize() override {}
	void finalize_core() override {}
	bool _check_internal_feature_support(const String &p_feature) override { return false; }

public:
	Vector<String> get_video_adapter_driver_info() const override { return Vector<String>(); }
	String get_stdin_string(int64_t p_buffer_size = 1024) override { return String(); }
	PackedByteArray get_stdin_buffer(int64_t p_buffer_size = 1024) override { return PackedByteArray(); }
	Error get_entropy(uint8_t *r_buffer, int p_bytes) override { return ERR_UNAVAILABLE; }
	Error execute(const String &p_path, const List<String> &p_arguments, String *r_pipe = nullptr, int *r_exitcode = nullptr, bool read_stderr = false, Mutex *p_pipe_mutex = nullptr, bool p_open_console = false) override { return ERR_UNAVAILABLE; }
	Error create_process(const String &p_path, const List<String> &p_arguments, ProcessID *r_child_id = nullptr, bool p_open_console = false) override { return ERR_UNAVAILABLE; }
	Error kill(const ProcessID &p_pid) override { return ERR_UNAVAILABLE; }
	bool is_process_running(const ProcessID &p_pid) const override { return false; }
	int get_process_exit_code(const ProcessID &p_pid) const override { return -1; }
	bool has_environment(const String &p_var) const override { return false; }
	String get_environment(const String &p_var) const override { return String(); }
	void set_environment(const String &p_var, const String &p_value) const override {}
	void unset_environment(const String &p_var) const override {}
	String get_name() const override { return "Homot"; }
	String get_distribution_name() const override { return ""; }
	String get_version() const override { return ""; }
	MainLoop *get_main_loop() const override { return nullptr; }
	DateTime get_datetime(bool utc = false) const override { return DateTime(); }
	TimeZoneInfo get_time_zone_info() const override { return TimeZoneInfo(); }
	void delay_usec(uint32_t p_usec) const override {}
	uint64_t get_ticks_usec() const override { return 0; }
};

// ---------------------------------------------------------------------------
// Platform file/dir access
// ---------------------------------------------------------------------------

static void register_platform_file_access() {
#ifdef _WIN32
	FileAccess::make_default<FileAccessWindows>(FileAccess::ACCESS_RESOURCES);
	FileAccess::make_default<FileAccessWindows>(FileAccess::ACCESS_USERDATA);
	FileAccess::make_default<FileAccessWindows>(FileAccess::ACCESS_FILESYSTEM);
	DirAccess::make_default<DirAccessWindows>(DirAccess::ACCESS_RESOURCES);
	DirAccess::make_default<DirAccessWindows>(DirAccess::ACCESS_USERDATA);
	DirAccess::make_default<DirAccessWindows>(DirAccess::ACCESS_FILESYSTEM);
#endif
}

// ---------------------------------------------------------------------------
// GDScript module init/deinit
// ---------------------------------------------------------------------------

static GDScriptLanguage *gd_language = nullptr;
static Ref<ResourceFormatLoaderGDScript> gd_loader;
static Ref<ResourceFormatSaverGDScript> gd_saver;

static void init_gdscript_module() {
	GDREGISTER_CLASS(GDScript);
	gd_language = memnew(GDScriptLanguage);
	ScriptServer::register_language(gd_language);
	gd_loader.instantiate();
	ResourceLoader::add_resource_format_loader(gd_loader);
	gd_saver.instantiate();
	ResourceSaver::add_resource_format_saver(gd_saver);
	GDScriptUtilityFunctions::register_functions();
}

static void deinit_gdscript_module() {
	GDScriptUtilityFunctions::unregister_functions();
	ResourceLoader::remove_resource_format_loader(gd_loader);
	gd_loader.unref();
	ResourceSaver::remove_resource_format_saver(gd_saver);
	gd_saver.unref();
	ScriptServer::unregister_language(gd_language);
	memdelete(gd_language);
	gd_language = nullptr;
}

// ---------------------------------------------------------------------------
// Engine bootstrap / cleanup
// ---------------------------------------------------------------------------

static Engine *engine_inst = nullptr;
static ProjectSettings *project_settings_inst = nullptr;
static TranslationServer *translation_server_inst = nullptr;
static TextServerManager *text_server_manager_inst = nullptr;
static GDScriptCache *gdscript_cache_inst = nullptr;

static void engine_bootstrap() {
	engine_inst = memnew(Engine);
	register_core_types();
	register_platform_file_access();

	project_settings_inst = memnew(ProjectSettings);
	register_core_settings();

	translation_server_inst = memnew(TranslationServer);

	text_server_manager_inst = memnew(TextServerManager);
	{
		Ref<TextServerDummy> ts;
		ts.instantiate();
		text_server_manager_inst->add_interface(ts);
		text_server_manager_inst->set_primary_interface(ts);
	}

	register_early_core_singletons();
	register_core_singletons();

	init_gdscript_module();
	gdscript_cache_inst = memnew(GDScriptCache);

	initialize_holymolly_module(MODULE_INITIALIZATION_LEVEL_SERVERS);
}

static void engine_cleanup() {
	if (linter::LinterDB::get_singleton()) {
		memdelete(linter::LinterDB::get_singleton());
	}
	uninitialize_holymolly_module(MODULE_INITIALIZATION_LEVEL_SERVERS);
	GDScriptCache::clear();
	memdelete(gdscript_cache_inst);
	deinit_gdscript_module();

	memdelete(text_server_manager_inst);
	memdelete(translation_server_inst);
	memdelete(project_settings_inst);
	memdelete(engine_inst);

	unregister_core_types();
}

// ---------------------------------------------------------------------------
// Load linterdb: from --db flag or embedded data.
// ---------------------------------------------------------------------------

static bool load_linterdb(const char *db_path_override) {
	linter::LinterDB *db = memnew(linter::LinterDB);
	Error err;

	if (db_path_override) {
		err = db->load_from_json(String::utf8(db_path_override));
	} else {
		err = db->load_from_compressed(linterdb_compressed_data, linterdb_compressed_size, linterdb_uncompressed_size);
	}

	if (err != OK) {
		memdelete(db);
		return false;
	}
	return true;
}

// ---------------------------------------------------------------------------
// Subcommand: lint
// ---------------------------------------------------------------------------

static int cmd_lint(int argc, char *argv[], const char *db_override) {
	static const int MAX_TARGETS = 256;
	const char *targets[MAX_TARGETS];
	int target_count = 0;

	for (int i = 0; i < argc; i++) {
		if (argv[i][0] == '-') {
			fprintf(stderr, "Unknown lint option: %s\n", argv[i]);
			return 1;
		} else {
			if (target_count < MAX_TARGETS) {
				targets[target_count++] = argv[i];
			}
		}
	}

	if (target_count == 0) {
		fprintf(stderr, "ERROR: No files or directories specified.\nUsage: homot lint [--db <path>] <path> [<path> ...]\n");
		return 1;
	}

	Vector<String> lint_paths;
	for (int i = 0; i < target_count; i++) {
		lint_paths.push_back(String::utf8(targets[i]));
	}

	// Load DB via the shared loader (uses embedded or override).
	if (!load_linterdb(db_override)) {
		fprintf(stderr, "ERROR: Failed to load linterdb.\n");
		return 1;
	}

	// run_lint with empty db_path since DB is already loaded.
	int result = linter::run_lint(lint_paths, String());
	return result;
}

// ---------------------------------------------------------------------------
// Subcommand: lsp
// ---------------------------------------------------------------------------

static int cmd_lsp(const char *db_override) {
	if (!load_linterdb(db_override)) {
		fprintf(stderr, "ERROR: Failed to load linterdb.\n");
		return 1;
	}

	lsp::Server server;
	// DB is already loaded; set empty path so server doesn't try to reload.
	server.set_db_path(String());

	while (true) {
		Dictionary msg = lsp::Transport::read_message();
		if (msg.is_empty()) {
			break;
		}
		if (!server.process_message(msg)) {
			break;
		}
	}

	return 0;
}

// ---------------------------------------------------------------------------
// Subcommand: lspa
// ---------------------------------------------------------------------------

static int cmd_lspa(const char *db_override) {
	if (!load_linterdb(db_override)) {
		fprintf(stderr, "ERROR: Failed to load linterdb.\n");
		return 1;
	}

	lspa::Server server;
	server.set_db_path(String());

	while (true) {
		Dictionary msg = lsp::Transport::read_message();
		if (msg.is_empty()) {
			break;
		}
		if (!server.process_message(msg)) {
			break;
		}
	}

	return 0;
}

// ---------------------------------------------------------------------------
// Help
// ---------------------------------------------------------------------------

static void print_help() {
	printf("Usage: homot <command> [options] [args...]\n\n");
	printf("Commands:\n");
	printf("  lint <path> [<path>...]   Lint .gd/.hm/.hmc scripts\n");
	printf("  lsp                       Start GDScript Language Server (stdio)\n");
	printf("  lspa                      Start Language Server for Agents (stdio)\n");
	printf("\nGlobal Options:\n");
	printf("  --db <path>    Override embedded linterdb with external JSON file\n");
	printf("  --help, -h     Show this help message\n");
	printf("\nExamples:\n");
	printf("  homot lint scripts/\n");
	printf("  homot lsp\n");
	printf("  homot lspa\n");
	printf("  homot lint --db custom.json scripts/player.gd\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

int main(int argc, char *argv[]) {
	// Pre-bootstrap CLI parsing (raw C strings only).
	const char *command = nullptr;
	const char *db_override = nullptr;
	int cmd_argc = 0;
	char **cmd_argv = nullptr;

	for (int i = 1; i < argc; i++) {
		if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
			_homot_restore_stderr();
			print_help();
			return 0;
		} else if (strcmp(argv[i], "--db") == 0 && i + 1 < argc) {
			db_override = argv[++i];
		} else if (!command) {
			command = argv[i];
			// Remaining args go to the subcommand.
			cmd_argc = argc - i - 1;
			cmd_argv = argv + i + 1;
			break;
		}
	}

	if (!command) {
		_homot_restore_stderr();
		print_help();
		return 1;
	}

	// Engine bootstrap.
	OS_Homot os_homot;
	set_current_thread_safe_for_nodes(true);
	engine_bootstrap();

	_homot_restore_stderr();

	// Dispatch subcommand.
	int result = 1;

	if (strcmp(command, "lint") == 0) {
		result = cmd_lint(cmd_argc, cmd_argv, db_override);
	} else if (strcmp(command, "lsp") == 0) {
		result = cmd_lsp(db_override);
	} else if (strcmp(command, "lspa") == 0) {
		result = cmd_lspa(db_override);
	} else {
		fprintf(stderr, "Unknown command: %s\nUse --help for usage information.\n", command);
	}

	engine_cleanup();
	return result;
}

#endif // HOMOT
